[package]
name = "aristotles_number_puzzle_genetic"
version = "0.1.0"
authors = ["Marco Neumann <marco@crepererum.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"

[profile.release]
debug = true
